# Generated by Django 5.2.4 on 2025-07-16 00:22

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employee_id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
                blank=True,
                length=10,
                max_length=20,
                null=True,
                prefix="",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="unit_id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
                blank=True,
                length=10,
                max_length=20,
                null=True,
                prefix="",
                unique=True,
            ),
        ),
    ]
