# Generated by Django 5.2.4 on 2025-07-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_employee_name_remove_employee_section_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="next_of_kin",
            new_name="next_of_kin_name",
        ),
        migrations.AddField(
            model_name="employee",
            name="next_of_kin_phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
